#############################
#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#
# This GUI module was generated by PAGE, Python Automatic GUI Generator.
# This module provides the code for the framework of the SpyRover GUI.
# The functionality for this GUI is coded in SpyRoverGUI_support.py
#
# Author- Aaron Safran
############################

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import SpyRoverGUI_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Spy_Rover_Control_Station (root)
    SpyRoverGUI_support.init(root, top)
    root.mainloop()

w = None
def create_Spy_Rover_Control_Station(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Spy_Rover_Control_Station (w)
    SpyRoverGUI_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Spy_Rover_Control_Station():
    global w
    w.destroy()
    w = None


class Spy_Rover_Control_Station:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font11 = "-family {Segoe UI} -size 15 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family {Segoe UI} -size 12 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font19 = "-family {Segoe UI} -size 14 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font20 = "-family {Segoe UI} -size 13 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font23 = "-family {Segoe UI} -size 12 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font25 = "-family {Segoe UI} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font29 = "-family {Segoe UI} -size 22 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("559x430+825+120")
        top.title("Spy Rover Control Station")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        top.bind('<Key>',lambda e:SpyRoverGUI_support.Reaction(e))



        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook1 = ttk.Notebook(top)
        self.TNotebook1.place(relx=0.02, rely=0.02, relheight=0.94
                , relwidth=0.96)
        self.TNotebook1.configure(width=534)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t1 = ttk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(0, text="Basic Controls",underline="-1",)
        self.TNotebook1_t2 = ttk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t2, padding=3)
        self.TNotebook1.tab(1, text="Rover Settings",underline="-1",)

        self.lblW = Label(self.TNotebook1_t1)
        self.lblW.place(relx=0.7, rely=0.14, height=41, width=47)
        self.lblW.configure(activebackground="#f9f9f9")
        self.lblW.configure(activeforeground="black")
        self.lblW.configure(background="#a8a8ff")
        self.lblW.configure(borderwidth="5")
        self.lblW.configure(disabledforeground="#a3a3a3")
        self.lblW.configure(font=font11)
        self.lblW.configure(foreground="#000000")
        self.lblW.configure(highlightbackground="#d9d9d9")
        self.lblW.configure(highlightcolor="black")
        self.lblW.configure(relief=RAISED)
        self.lblW.configure(text='''W''')

        self.lblPrompt = Label(self.TNotebook1_t1)
        self.lblPrompt.place(relx=0.04, rely=0.03, height=31, width=447)
        self.lblPrompt.configure(activebackground="#f9f9f9")
        self.lblPrompt.configure(activeforeground="black")
        self.lblPrompt.configure(background="#d9d9d9")
        self.lblPrompt.configure(disabledforeground="#a3a3a3")
        self.lblPrompt.configure(font=font12)
        self.lblPrompt.configure(foreground="#000000")
        self.lblPrompt.configure(highlightbackground="#d9d9d9")
        self.lblPrompt.configure(highlightcolor="black")
        self.lblPrompt.configure(text='''Use the keys on your keyboard to control the rover''')

        self.lblA1 = Label(self.TNotebook1_t1)
        self.lblA1.place(relx=0.6, rely=0.24, height=41, width=47)
        self.lblA1.configure(activebackground="#f9f9f9")
        self.lblA1.configure(activeforeground="black")
        self.lblA1.configure(background="#a8a8ff")
        self.lblA1.configure(borderwidth="5")
        self.lblA1.configure(disabledforeground="#a3a3a3")
        self.lblA1.configure(font=font11)
        self.lblA1.configure(foreground="#000000")
        self.lblA1.configure(highlightbackground="#d9d9d9")
        self.lblA1.configure(highlightcolor="black")
        self.lblA1.configure(relief=RAISED)
        self.lblA1.configure(text='''A''')

        self.lblS = Label(self.TNotebook1_t1)
        self.lblS.place(relx=0.7, rely=0.24, height=41, width=47)
        self.lblS.configure(activebackground="#f9f9f9")
        self.lblS.configure(activeforeground="black")
        self.lblS.configure(background="#a8a8ff")
        self.lblS.configure(borderwidth="5")
        self.lblS.configure(disabledforeground="#a3a3a3")
        self.lblS.configure(font=font11)
        self.lblS.configure(foreground="#000000")
        self.lblS.configure(highlightbackground="#d9d9d9")
        self.lblS.configure(highlightcolor="black")
        self.lblS.configure(relief=RAISED)
        self.lblS.configure(text='''S''')

        self.lblD = Label(self.TNotebook1_t1)
        self.lblD.place(relx=0.79, rely=0.24, height=41, width=47)
        self.lblD.configure(activebackground="#f9f9f9")
        self.lblD.configure(activeforeground="black")
        self.lblD.configure(background="#a8a8ff")
        self.lblD.configure(borderwidth="5")
        self.lblD.configure(disabledforeground="#a3a3a3")
        self.lblD.configure(font=font11)
        self.lblD.configure(foreground="#000000")
        self.lblD.configure(highlightbackground="#d9d9d9")
        self.lblD.configure(highlightcolor="black")
        self.lblD.configure(relief=RAISED)
        self.lblD.configure(text='''D''')

        self.btnStart = Button(self.TNotebook1_t1)
        self.btnStart.place(relx=0.17, rely=0.22, height=61, width=85)
        self.btnStart.configure(activebackground="#d9d9d9")
        self.btnStart.configure(activeforeground="#000000")
        self.btnStart.configure(background="#d9d9d9")
        self.btnStart.configure(disabledforeground="#a3a3a3")
        self.btnStart.configure(font=font19)
        self.btnStart.configure(foreground="#000000")
        self.btnStart.configure(highlightbackground="#d9d9d9")
        self.btnStart.configure(highlightcolor="black")
        self.btnStart.configure(pady="0")
        self.btnStart.configure(text='''Start''')
        self.btnStart.configure(width=85)
        self.btnStart.bind('<Button-1>',lambda e:SpyRoverGUI_support.BtnStart(e))

        self.lblSpacebar = Label(self.TNotebook1_t1)
        self.lblSpacebar.place(relx=0.57, rely=0.43, height=41, width=197)
        self.lblSpacebar.configure(activebackground="#f9f9f9")
        self.lblSpacebar.configure(activeforeground="black")
        self.lblSpacebar.configure(background="#a8a8ff")
        self.lblSpacebar.configure(borderwidth="5")
        self.lblSpacebar.configure(disabledforeground="#a3a3a3")
        self.lblSpacebar.configure(font=font12)
        self.lblSpacebar.configure(foreground="#000000")
        self.lblSpacebar.configure(highlightbackground="#d9d9d9")
        self.lblSpacebar.configure(highlightcolor="black")
        self.lblSpacebar.configure(relief=RAISED)
        self.lblSpacebar.configure(text='''Spacebar (Stop)''')
        self.lblSpacebar.configure(width=197)

        #Label with "Start" prompt on Basic Controls tab
        #Appears when user tries to move without clicking "Start" btn
        self.lblClickPrompt2 = Label(self.TNotebook1_t1)
        self.lblClickPrompt2.place(relx=0.15, rely=0.7, height=31, width=387)
        self.lblClickPrompt2.configure(activebackground="#f9f9f9")
        self.lblClickPrompt2.configure(activeforeground="black")
        self.lblClickPrompt2.configure(background="#d9d9d9")
        self.lblClickPrompt2.configure(disabledforeground="#a3a3a3")
        self.lblClickPrompt2.configure(font=font25)
        self.lblClickPrompt2.configure(foreground="#d9d9d9")
        self.lblClickPrompt2.configure(highlightbackground="#d9d9d9")
        self.lblClickPrompt2.configure(highlightcolor="black")
        self.lblClickPrompt2.configure(text='''Click 'Start' button to move rover''')
        self.lblClickPrompt2.configure(width=387)

        self.btnSet = Button(self.TNotebook1_t2)
        self.btnSet.place(relx=0.09, rely=0.08, height=45, width=133)
        self.btnSet.configure(activebackground="#d9d9d9")
        self.btnSet.configure(activeforeground="#000000")
        self.btnSet.configure(background="#d9d9d9")
        self.btnSet.configure(disabledforeground="#a3a3a3")
        self.btnSet.configure(font=font20)
        self.btnSet.configure(foreground="#000000")
        self.btnSet.configure(highlightbackground="#d9d9d9")
        self.btnSet.configure(highlightcolor="black")
        self.btnSet.configure(pady="0")
        self.btnSet.configure(text='''Change Setting''')
        self.btnSet.configure(width=133)
        self.btnSet.bind('<Button-1>',lambda e:SpyRoverGUI_support.changeSettings(e))

        self.spbxMotorSpeed = Spinbox(self.TNotebook1_t2, from_=0.0, to=1.0)
        self.spbxMotorSpeed.place(relx=0.6, rely=0.32, relheight=0.08
                , relwidth=0.15)
        self.spbxMotorSpeed.configure(activebackground="#f9f9f9")
        self.spbxMotorSpeed.configure(background="white")
        self.spbxMotorSpeed.configure(buttonbackground="#d9d9d9")
        self.spbxMotorSpeed.configure(disabledforeground="#a3a3a3")
        self.spbxMotorSpeed.configure(font=font19)
        self.spbxMotorSpeed.configure(foreground="black")
        self.spbxMotorSpeed.configure(highlightbackground="black")
        self.spbxMotorSpeed.configure(highlightcolor="black")
        self.spbxMotorSpeed.configure(increment="0.1")
        self.spbxMotorSpeed.configure(insertbackground="black")
        self.spbxMotorSpeed.configure(justify=CENTER)
        self.spbxMotorSpeed.configure(selectbackground="#c4c4c4")
        self.spbxMotorSpeed.configure(selectforeground="black")
        READONLY = 'readonly'
        self.spbxMotorSpeed.configure(state=READONLY)
        self.spbxMotorSpeed.configure(takefocus="false")
        self.spbxMotorSpeed.configure(to="1.0")
        self.spbxMotorSpeed.configure(width=78)
        self.spbxMotorSpeed.configure(wrap=1)

        self.lblSpeedPrompt = Label(self.TNotebook1_t2)
        self.lblSpeedPrompt.place(relx=0.02, rely=0.3, height=31, width=287)
        self.lblSpeedPrompt.configure(background="#d9d9d9")
        self.lblSpeedPrompt.configure(disabledforeground="#a3a3a3")
        self.lblSpeedPrompt.configure(font=font19)
        self.lblSpeedPrompt.configure(foreground="#000000")
        self.lblSpeedPrompt.configure(justify=LEFT)
        self.lblSpeedPrompt.configure(text='''Change motor speed:''')
        self.lblSpeedPrompt.configure(width=287)

        self.lblDefaultSpeed = Label(self.TNotebook1_t2)
        self.lblDefaultSpeed.place(relx=0.04, rely=0.38, height=41, width=267)
        self.lblDefaultSpeed.configure(background="#d9d9d9")
        self.lblDefaultSpeed.configure(disabledforeground="#a3a3a3")
        self.lblDefaultSpeed.configure(font=font19)
        self.lblDefaultSpeed.configure(foreground="#000000")
        self.lblDefaultSpeed.configure(justify=LEFT)
        self.lblDefaultSpeed.configure(text='''(Default speed is 0.4)''')
        self.lblDefaultSpeed.configure(width=267)

        self.BtnSetSpeed = Button(self.TNotebook1_t2)
        self.BtnSetSpeed.place(relx=0.79, rely=0.3, height=61, width=87)
        self.BtnSetSpeed.configure(activebackground="#d9d9d9")
        self.BtnSetSpeed.configure(activeforeground="#000000")
        self.BtnSetSpeed.configure(background="#d9d9d9")
        self.BtnSetSpeed.configure(disabledforeground="#a3a3a3")
        self.BtnSetSpeed.configure(font=font12)
        self.BtnSetSpeed.configure(foreground="#000000")
        self.BtnSetSpeed.configure(highlightbackground="#d9d9d9")
        self.BtnSetSpeed.configure(highlightcolor="black")
        self.BtnSetSpeed.configure(pady="0")
        self.BtnSetSpeed.configure(text='''Set Speed''')
        self.BtnSetSpeed.configure(width=87)
        self.BtnSetSpeed.bind('<Button-1>',lambda e:SpyRoverGUI_support.SetSpeed(e))

        #Label with "change setting" prompt on Rover Settings tab
        #Appear when user tries to change settings without clicking "Change settings" btn
        self.lblClickPrompt1 = Label(self.TNotebook1_t2)
        self.lblClickPrompt1.place(relx=0.42, rely=0.11, height=31, width=297)
        self.lblClickPrompt1.configure(background="#d9d9d9")
        self.lblClickPrompt1.configure(disabledforeground="#a3a3a3")
        self.lblClickPrompt1.configure(font=font23)
        self.lblClickPrompt1.configure(foreground="#d9d9d9")
        self.lblClickPrompt1.configure(text='''Click 'Change Setting' button ''')
        self.lblClickPrompt1.configure(width=297)

        self.btnNightVision = Button(self.TNotebook1_t2)
        self.btnNightVision.place(relx=0.15, rely=0.65, height=92, width=368)
        self.btnNightVision.configure(activebackground="#d9d9d9")
        self.btnNightVision.configure(activeforeground="#000000")
        self.btnNightVision.configure(background="#d9d9d9")
        self.btnNightVision.configure(disabledforeground="#a3a3a3")
        self.btnNightVision.configure(font=font29)
        self.btnNightVision.configure(foreground="#000000")
        self.btnNightVision.configure(highlightbackground="#d9d9d9")
        self.btnNightVision.configure(highlightcolor="black")
        self.btnNightVision.configure(pady="0")
        self.btnNightVision.configure(text='''Activate Night Vision''')
        self.btnNightVision.configure(width=368)
        self.btnNightVision.bind('<Button-1>',lambda e:SpyRoverGUI_support.SetLED(e))

        self.menubar = Menu(top,font=font9,bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)








if __name__ == '__main__':
    vp_start_gui()

